export const queryKeys = {
  companies: {
    all: ['companies'] as const,
    detail: (id: string) => ['companies', id] as const,
    config: (id: string) => ['companies', id, 'config'] as const,
    toolConfig: (id: string) => ['companies', id, 'tool-config'] as const,
    users: (id: string) => ['companies', id, 'users'] as const,
    usage: (id: string, months: number) => ['companies', id, 'usage', months] as const,
    usageCurrent: (id: string) => ['companies', id, 'usage', 'current'] as const,
    analytics: (id: string, months: number) => ['companies', id, 'analytics', months] as const,
    dataSources: (id: string) => ['companies', id, 'data-sources'] as const,
    agentMetrics: (id: string, windowDays: number) => ['companies', id, 'agent-metrics', windowDays] as const,
    plan: (id: string) => ['companies', id, 'plan'] as const,
    billingEvents: (id: string) => ['companies', id, 'billing-events'] as const,
  },
  platform: {
    summary: (months: number) => ['platform', 'summary', months] as const,
    defaults: ['platform', 'defaults'] as const,
    models: ['platform', 'models'] as const,
    toolPlans: ['platform', 'tool-plans'] as const,
    dataSources: (params?: string) => ['platform', 'data-sources', params ?? ''] as const,
    dataSourceTypes: ['platform', 'data-source-types'] as const,
    plans: ['platform', 'plans'] as const,
    planDetail: (id: string) => ['platform', 'plans', id] as const,
    revenue: ['platform', 'revenue'] as const,
    emailTemplates: ['platform', 'email-templates'] as const,
    emailTemplate: (slug: string) => ['platform', 'email-templates', slug] as const,
  },
}
